languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Portfolio"
copyright = "&copy; 2024 All Rights Reserved."

[params.author]
  name = "Jhonas Caba√±ero"
  image = "img/image.png"
  headline = "AWS Certified Cloud Practitioner | Degree Holder (Information Technology) | Into ‚òÅÔ∏è | Loves to build computer üñ•Ô∏è"
   links = [
     { email = "mailto:mr.jhonas.cloud@gmail.com" },
     { github = "https://github.com/jhonas-cloud" },
     { linkedin = "https://www.linkedin.com/in/jhonascaba√±ero" },
   ]