languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

#title = "My Portfolio"
copyright = "&copy; 2026 All Rights Reserved."

[params.author]
  name = "Jhonas Cabañero"
  image = "img/image.png"
   links = [
     { email = "mailto:mr.jhonas.cloud@gmail.com" },
     { github = "https://github.com/jhonas-cloud" },
     { linkedin = "https://www.linkedin.com/in/jhonascabañero" },
   ]
